// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mvc4BootstrapLessDemo.Controllers {
    public partial class PagesController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PagesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PagesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PagesController Actions { get { return MVC.Pages; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Pages";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Pages";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string GetStarted = "GetStarted";
            public readonly string Scaffolding = "Scaffolding";
            public readonly string BaseCss = "BaseCss";
            public readonly string Components = "Components";
            public readonly string Javascript = "Javascript";
            public readonly string Customize = "Customize";
            public readonly string Extend = "Extend";
            public readonly string Hero = "Hero";
            public readonly string Fluid = "Fluid";
            public readonly string Starter = "Starter";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string GetStarted = "GetStarted";
            public const string Scaffolding = "Scaffolding";
            public const string BaseCss = "BaseCss";
            public const string Components = "Components";
            public const string Javascript = "Javascript";
            public const string Customize = "Customize";
            public const string Extend = "Extend";
            public const string Hero = "Hero";
            public const string Fluid = "Fluid";
            public const string Starter = "Starter";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string BaseCss = "~/Views/Pages/BaseCss.cshtml";
            public readonly string Components = "~/Views/Pages/Components.cshtml";
            public readonly string Customize = "~/Views/Pages/Customize.cshtml";
            public readonly string Extend = "~/Views/Pages/Extend.cshtml";
            public readonly string GetStarted = "~/Views/Pages/GetStarted.cshtml";
            public readonly string Javascript = "~/Views/Pages/Javascript.cshtml";
            public readonly string Scaffolding = "~/Views/Pages/Scaffolding.cshtml";
            static readonly _examples s_examples = new _examples();
            public _examples examples { get { return s_examples; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _examples{
                public readonly string Fluid = "~/Views/Pages/examples/Fluid.cshtml";
                public readonly string Hero = "~/Views/Pages/examples/Hero.cshtml";
                public readonly string Starter = "~/Views/Pages/examples/Starter.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_PagesController: Mvc4BootstrapLessDemo.Controllers.PagesController {
        public T4MVC_PagesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult GetStarted() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetStarted);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Scaffolding() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Scaffolding);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BaseCss() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.BaseCss);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Components() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Components);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Javascript() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Javascript);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Customize() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Customize);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Extend() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Extend);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Hero() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Hero);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Fluid() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Fluid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Starter() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Starter);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
